### ISSUE TITLE
你好，通过Jenkins创建模拟器自动化测试时怎么将LeakCanary收集到的日志信息通过邮件发送啊。

### ISSUE THREAD

**Issue by lhholylight** [hehonghui/app-test-arch#1]
你好，通过Jenkins创建模拟器自动化测试时怎么将LeakCanary收集到的日志信息通过邮件发送啊。

**Comment by hehonghui** [comment]
@lhholylight 看 leakfortest 项目中的 LeakDumpService, 在发生leak时将leak信息写入到sd卡的特定目录下，测试完之后通过adb命令pull到 jenkins的宿主机上，然后通过邮件发送即可.
